pipeline {
  agent any
  environment {
    DOCKERHUB_PASS = credentials('docker-pass')
  }
  stages {
    stage ("Building the web app into a docker image"){
      steps {
        script {
          checkout scm
          sh 'pwd'
          sh 'whoami'
          def mvnHome = tool name: 'Maven3', type: 'maven'
          def mvnCMD = "${mvnHome}/bin/mvn"
          sh "${mvnCMD} -f surveyapi/pom.xml clean package"
          sh "docker login -u cparupal -p $DOCKERHUB_PASS_PSW"
          sh 'mv surveyapi/Dockerfile surveyapi/target/'
          sh "docker build -t cparupal/studentsurveyapi:${env.BUILD_ID} surveyapi/target"
          
        }
      }
    }
    
    stage("Pushing Image to Dockerhub"){
      steps{
        script{
          sh "docker push cparupal/studentsurveyapi:${env.BUILD_ID}"
        }
      }
    }

  }
}
