pipeline {
  agent any
  environment {
    DOCKERHUB_PASS = credentials('docker-pass')
  }
  stages {
    stage ("Building the web app into a docker image"){
      steps {
        script {
          checkout scm
          sh 'pwd'
          sh 'whoami'
          def mvnHome = tool name: 'Maven3', type: 'maven'
          def mvnCMD = "${mvnHome}/bin/mvn"
          sh "${mvnCMD} -f surveyapi/pom.xml clean package"
          sh "docker login -u cparupal -p $DOCKERHUB_PASS_PSW"
          sh 'mv surveyapi/Dockerfile surveyapi/target/'
          sh "docker build -t cparupal/studentsurveyapi:${env.BUILD_ID} surveyapi/target"
          
        }
      }
    }
    
    stage("Pushing Image to Dockerhub"){
      steps{
        script{
          sh "docker push cparupal/studentsurveyapi:${env.BUILD_ID}"
        }
      }
    }
    
    stage("Updating deployment.yaml file with new Build"){
      steps{
        script{
          sh 'rm -rf SWE645HW3_API'
          sh "git config --global user.email 'chetana.p98@gmail.com'"
          sh 'git remote set-url origin git@github.com:cparupal/SWE645HW3_API.git'
          sh "git clone git@github.com:cparupal/SWE645HW3_API.git"
          sh 'cd SWE645HW3_API'
          sh 'git checkout main'
          sh 'cd surveyapi'
          sh "sed -i 's/studentsurveyapi:.*/studentsurveyapi:${env.BUILD_ID}/' SWE645HW3_API/surveyapi/deployment.yaml"
          sh 'git add deployment.yaml'
          sh "git commit -m 'Uploading deployment.yaml with build image ${env.BUILD_ID}'"
          sh "git push"
        }
      }
    }

  }
}
